button_enter = '//body/div[3]/header/div/div[1]//div[2]/ul/li[3]/a'
button_reg = '//body/section[4]//div[2]/div[2]//div[2]/a'
finish_button_reg = '//body/div[3]/main/div//div//div[3]/form/fieldset[2]/div[4]/input'
finish_button_reg1 = '//body/div[3]/main/div//div//div[3]/form/div/div[1]/button/span'
placeholder_field = '//body/div[3]/main/div//div//div[3]/form/fieldset[1]/div[5]/input'
nick_text = '/html/body/div[3]/main/div/div/div/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/p[text()]'
assert_error = '//body/div[3]/main/div//div//div[3]/form/fieldset[1]/div[2]//div[contains(text(), " ")]'

nick_1 = '//body/div[3]/main/div//div//div[3]/form/fieldset[1]/div[2]/div/input'
lastname_1 = '//body/div[3]/main/div//div//div[3]/form/fieldset[1]/div[3]/div/input'
phone_1 = '//body/div[3]/main/div//div//div[3]/form/fieldset[1]/div[4]//div/input'
email_1 = '//body/div[3]/main/div//div//div[3]/form/fieldset[2]/div[1]/div/input'
address_1 = '//body/div[3]/main/div//div//div[3]/form/fieldset[2]/div[2]/div/input'
password_1 = '//body/div[3]/main/div//div//div[3]/form/fieldset[2]/div[3]/div/input'
assert_error2 = '//body/div[3]/main/div//div//div[3]/form/fieldset[1]/div[3]/div/div'
assert_error3 = '//body/div[3]/main/div//div//div[3]/form/fieldset[2]/div[1]/div/div'
